#pragma once
#include "driver/gpio.h"

#define PIN_COUNT 49

#define GPIO_ARM_SERVO3 GPIO_NUM_1 // Grapple (rx)
#define GPIO_ARM_SERVO4 GPIO_NUM_2 // arm (ry)
#define MOTOR1SENSOR2 GPIO_NUM_3
#define GPIO_UNUSED1 GPIO_NUM_4
#define GPIO_BUZZER1 GPIO_NUM_5
#define GPIO_SLEEP_BUTTON GPIO_NUM_6
#define GPIO_STEERING GPIO_NUM_7
#define MOTOR1SENSOR1 GPIO_NUM_8
#define MOTOR2SENSOR1 GPIO_NUM_9
#define MOTOR2SENSOR2 GPIO_NUM_10
#define MOTOR3SENSOR1 GPIO_NUM_11
#define MOTOR3SENSOR2 GPIO_NUM_12
#define MOTOR4SENSOR1 GPIO_NUM_13
#define MOTOR4SENSOR2 GPIO_NUM_14

#define GPIO_UNUSED_6 GPIO_NUM_35
#define GPIO_SCL GPIO_NUM_36
#define GPIO_SDA GPIO_NUM_37
#define GPIO_UNUSED_7 GPIO_NUM_38
#define GPIO_UNUSED_5 GPIO_NUM_39
#define GPIO_MOTOR_PWM1 GPIO_NUM_40
#define GPIO_MOTOR_PWM2 GPIO_NUM_41
#define GPIO_ARM_SERVO1 GPIO_NUM_42 // Base rotation (lx)
#define GPIO_ARM_SERVO2 GPIO_NUM_47 // Boom (ly)
#define GPIO_OUTPUT_LED GPIO_NUM_48

#define WHEEL_SIZE_MM 100